version: '3.5'
services:
  FluxoCaixa.database:
    container_name: "FluxoCaixa.database"
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    ports:
      - "8001:1433"
    volumes:
      - FluxoCaixa.database:/var/opt/mssql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
      SA_PASSWORD: "0^5N1eb8ll5@G!O22wnow#Vn@"
    networks:
      - FluxoCaixa

volumes:
  FluxoCaixa.database:
    name: FluxoCaixa.database
    external: false

networks:
  FluxoCaixa:
    name: FluxoCaixa
    driver: bridge